@baseUrl = http://localhost:3000

# Msg
###
GET {{baseUrl}}/messages/
?limit=10
&offset=0
###
GET {{baseUrl}}/messages/1
###
POST {{baseUrl}}/messages
Content-Type: application/json

  {
    "text": "test messag",
    "from": "Alice",
    "to": "Bob",
    "read": true,
    "created_at": "2025-04-15T18:11:43.241Z",
    "updated_at": "2025-04-15T18:11:43.241Z",
    "deleted_at": null
  }
###
PATCH  {{baseUrl}}/messages/2
Content-Type: application/json

  {
    "text": "Future messag",
    "from": "John",
    "to": "Jane Doe",
    "read": true,
    "created_at": "2025-04-15T18:11:43.241Z",
    "updated_at": "2025-04-15T18:11:43.241Z",
    "deleted_at": null
  }

###
DELETE {{baseUrl}}/messages/1
